// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACVOun80oYO0bmq69t9h_wiM8dVeW-sVw',
    appId: '1:1068288647979:web:871a5bc47d774c9f991b6e',
    messagingSenderId: '1068288647979',
    projectId: 'maps-16e15',
    authDomain: 'maps-16e15.firebaseapp.com',
    storageBucket: 'maps-16e15.appspot.com',
    measurementId: 'G-ZL53L342VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN6bF9iQxFcD_T0h3jaXkjeX5wSwiPKCA',
    appId: '1:1068288647979:android:9e43c8f86df7013c991b6e',
    messagingSenderId: '1068288647979',
    projectId: 'maps-16e15',
    storageBucket: 'maps-16e15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQij3otS2CxNif39wrxFHN0BOjCA1AUM',
    appId: '1:1068288647979:ios:b126f2676c1c1b15991b6e',
    messagingSenderId: '1068288647979',
    projectId: 'maps-16e15',
    storageBucket: 'maps-16e15.appspot.com',
    iosClientId: '1068288647979-vumkgqcg6vqhsi6u0556iregea2cr5u7.apps.googleusercontent.com',
    iosBundleId: 'com.khaterCS.maps',
  );
}
